spring:
  application:
    name: publisher-change-food-card
  datasource:
    oracle:
      url: jdbc:oracle:thin:@localhost:1521:XE
      username: gru
      password: root
      driverClassName: oracle.jdbc.OracleDriver
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres_db
      username: user
      password: root
      driverClassName: org.postgresql.Driver

  files:
    dir: D:\gpb_tasks\generator_file\generated