CREATE SEQUENCE GRU.GRU_VISTA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE GRU.GRU_VISTA_TAB (
    ID NUMBER PRIMARY KEY,
    SYSTEMACCOUNT VARCHAR2(32),
    CURRENCY VARCHAR2(3),
    XALFA NUMBER(23, 3),
    OPERATION VARCHAR2(2),
    TIME_STAMP TIMESTAMP,
    POM_ID NUMBER,
    UTERRARIO NUMBER,
    OLDTBAL NUMBER(23, 3),
    NEWTBAL NUMBER(23, 3),
    ADD_INFO VARCHAR2(100),
    FILE_ID NUMBER,
    FOC_STATUS VARCHAR2(64),
    FOC_TS TIMESTAMP,
    FOC_TYPE VARCHAR2(10)
);

-- Раздаем полные права пользователю gru
GRANT ALL ON GRU.GRU_VISTA_TAB TO GRU;
GRANT ALL ON GRU.GRU_VISTA_SEQ TO GRU;